name: bloc_firebase_auth_kit
description: A clean architecture Flutter package for Firebase authentication with BLoC state management, supporting email/password, Google, Facebook sign-in, and more.
version: 1.0.0
homepage: https://github.com/KlodianLula/bloc_firebase_auth_kit
repository: https://github.com/KlodianLula/bloc_firebase_auth_kit
issue_tracker: https://github.com/KlodianLula/bloc_firebase_auth_kit/issues

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_facebook_auth: ^7.0.1
  flutter_signin_button: ^2.0.0
  google_sign_in: ^6.1.0
  shared_preferences: ^2.2.2
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
